app = "masquerade"

[build]
builder = "paketobuildpacks/builder:base"
buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
BP_GO_TARGETS = "./cmd/masquerade"

[processes]
app = "masquerade -packageHost \"go.eigsys.de\" -githubOwner \"joeig\""

[http_service]
internal_port = 8493
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[http_service.checks]]
grace_period = "5s"
interval = "15s"
method = "GET"
path = "/.internal/health"
timeout = "5s"

[deploy]
strategy = "rolling"

[[metrics]]
port = 9091
path = "/metrics"
processes = ["app"]