---
name: Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55.2
      - name: Staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          $(go env GOPATH)/bin/staticcheck ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
      - name: Show test coverage
        run: make coverage
      - name: Check test coverage threshold
        id: coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.github/testcoverage.yml
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.21"
          check-latest: true
          go-package: ./...
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Build
        run: make build
